package vorm.jdbc

import com.weiglewilczek.slf4s.Logging
import java.sql.{ResultSet, PreparedStatement, Connection, Statement => JStatement}
import org.joda.time.DateTime

trait ExecutorAPI extends Logging {
  protected def connection: Connection

  protected def executeSelect(stmt: Statement): () => ResultSet = {
    throw new NotImplementedError
  }
  /**
   * @return How many rows updated
   */
  protected def update(stmt: Statement): Int = {
    logger.info("Executing update:\n" + stmt)
    executeUpdate(stmt)
  }
  /**
   * Either throw an exception or perform an insert and return autogenerated values result set for parsing
   * @return Autogenerated values
   */
  protected def insert(stmt: Statement): () => ResultSet = {
    logger.info("Executing insert:\n" + stmt)
    executeUpdateAndGetGeneratedKeys(stmt)
  }
  /**
   * @return How many rows deleted
   */
  protected def delete(stmt: Statement): Int = {
    logger.info("Executing delete:\n" + stmt)
    executeUpdate(stmt)
  }
  private def executeUpdateAndGetGeneratedKeys(stmt: Statement): () => ResultSet = {
    if (stmt.data.isEmpty) {
      val js = connection.createStatement()
      js.executeUpdate(stmt.sql).ensuring(_ == 1)
      js.getGeneratedKeys
    } else {
      val js = prepareJDBCStatement(stmt, true)
      js.executeUpdate().ensuring(_ == 1)
      js.getGeneratedKeys
    }
  }
  private def executeUpdate(stmt: Statement) = {
    if (stmt.data.isEmpty) connection.createStatement().executeUpdate(stmt.sql)
    else prepareJDBCStatement(stmt).executeUpdate()
  }
  private def prepareJDBCStatement(stmt: Statement, generatedKeys: Boolean = false) = {
    val s =
      connection.prepareStatement(
        stmt.sql,
        if (generatedKeys) JStatement.RETURN_GENERATED_KEYS else JStatement.NO_GENERATED_KEYS
      )

    stmt.data.zipWithIndex.foreach {
      case (v, i) => setJDBCStmtVar(s, i, v)
    }

    s
  }
  /**
   * @see <a href=http://docstore.mik.ua/orelly/java-ent/servlet/ch09_02.htm#ch09-22421>jdbc table
   */
  private def setJDBCStmtVar(s: PreparedStatement, i: Int, v: Any) {
    v match {
      case v: Boolean              => s.setBoolean(i, v)
      case v: String               => s.setString(i, v)
      case v: Int                  => s.setInt(i, v)
      case v: Integer              => s.setInt(i, v)
      case v: Long                 => s.setLong(i, v)
      case v: Float                => s.setFloat(i, v)
      case v: Double               => s.setDouble(i, v)
      case v: BigDecimal           => s.setBigDecimal(i, v.bigDecimal)
      case v: java.math.BigDecimal => s.setBigDecimal(i, v)
      case v: DateTime             => s.setDate(i, new java.sql.Date(v.getMillis))
    }
  }


}